import React, { useState } from 'react';
import { Save, CheckCircle } from 'lucide-react';
import { environmentConfigService } from '../services/environmentConfigService';
import type { AiBackend } from '../services/environmentConfigService';

export const MiscConfigPanel: React.FC = () => {
  const [aiBackend, setAiBackend] = useState<AiBackend>(() => environmentConfigService.getAiBackend());
  const [saved, setSaved] = useState(false);

  const handleSave = () => {
    const config = environmentConfigService.getConfiguration();
    environmentConfigService.setConfiguration({ ...config, aiBackend });
    setSaved(true);
    setTimeout(() => setSaved(false), 3000);
    console.log('[MiscConfigPanel] AI backend preference saved:', aiBackend);
  };

  return (
    <div className="space-y-6">
      <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-100">
        <h3 className="text-lg font-medium text-gray-900 mb-1">AI Backend for Summaries</h3>
        <p className="text-sm text-gray-500 mb-5">
          Choose which AI service is used when you click a link or summarize an email manually
          (outside of a Gempest automated run).
        </p>

        <div className="space-y-3">
          <label className="flex items-start gap-3 cursor-pointer group">
            <input
              type="radio"
              name="aiBackend"
              value="local"
              checked={aiBackend === 'local'}
              onChange={() => setAiBackend('local')}
              className="mt-1 text-blue-600 focus:ring-blue-500"
            />
            <div>
              <span className="font-medium text-gray-800 group-hover:text-blue-700">Use Local AI (Ollama)</span>
              <p className="text-sm text-gray-500 mt-0.5">
                Summaries are generated by your local Ollama instance. Requires Ollama to be running.
              </p>
            </div>
          </label>

          <label className="flex items-start gap-3 cursor-pointer group">
            <input
              type="radio"
              name="aiBackend"
              value="gemini"
              checked={aiBackend === 'gemini'}
              onChange={() => setAiBackend('gemini')}
              className="mt-1 text-blue-600 focus:ring-blue-500"
            />
            <div>
              <span className="font-medium text-gray-800 group-hover:text-blue-700">Use Gemini (Google AI)</span>
              <p className="text-sm text-gray-500 mt-0.5">
                Summaries are generated via the Gemini API. Requires a valid API key configured in the Gempest tab.
              </p>
            </div>
          </label>
        </div>

        <button
          onClick={handleSave}
          className="mt-6 flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
        >
          {saved ? <CheckCircle size={16} /> : <Save size={16} />}
          {saved ? 'Saved!' : 'Save'}
        </button>
      </div>
    </div>
  );
};
