import React, { useState } from 'react';
import { Save, CheckCircle, Moon, Sun } from 'lucide-react';
import { environmentConfigService } from '../services/environmentConfigService';
import type { AiBackend } from '../services/environmentConfigService';
import { themeService } from '../services/themeService';

export const MiscConfigPanel: React.FC = () => {
  const [aiBackend, setAiBackend] = useState<AiBackend>(() => environmentConfigService.getAiBackend());
  const [darkModeEnabled, setDarkModeEnabled] = useState<boolean>(() => environmentConfigService.isDarkModeEnabled());
  const [skipDeleteConfirmation, setSkipDeleteConfirmation] = useState<boolean>(() => environmentConfigService.shouldSkipDeleteConfirmation());
  const [saved, setSaved] = useState(false);

  const handleSave = () => {
    const config = environmentConfigService.getConfiguration();
    environmentConfigService.setConfiguration({ ...config, aiBackend, darkModeEnabled, skipDeleteConfirmation });
    themeService.applyDarkMode(darkModeEnabled);
    setSaved(true);
    setTimeout(() => setSaved(false), 3000);
    console.log('[MiscConfigPanel] Preferences saved:', { aiBackend, darkModeEnabled, skipDeleteConfirmation });
  };

  return (
    <div className="space-y-6">
      <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-sm border border-gray-100 dark:border-gray-700">
        <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100 mb-1">AI Backend for Summaries</h3>
        <p className="text-sm text-gray-500 dark:text-gray-300 mb-5">
          Choose which AI service is used when you click a link or summarize an email manually
          (outside of a Gempest automated run).
        </p>

        <div className="space-y-3">
          <label className="flex items-start gap-3 cursor-pointer group">
            <input
              type="radio"
              name="aiBackend"
              value="local"
              checked={aiBackend === 'local'}
              onChange={() => setAiBackend('local')}
              className="mt-1 text-blue-600 focus:ring-blue-500"
            />
            <div>
              <span className="font-medium text-gray-800 dark:text-gray-200 group-hover:text-blue-700">Use Local AI (Ollama)</span>
              <p className="text-sm text-gray-500 dark:text-gray-300 mt-0.5">
                Summaries are generated by your local Ollama instance. Requires Ollama to be running.
              </p>
            </div>
          </label>

          <label className="flex items-start gap-3 cursor-pointer group">
            <input
              type="radio"
              name="aiBackend"
              value="gemini"
              checked={aiBackend === 'gemini'}
              onChange={() => setAiBackend('gemini')}
              className="mt-1 text-blue-600 focus:ring-blue-500"
            />
            <div>
              <span className="font-medium text-gray-800 dark:text-gray-200 group-hover:text-blue-700">Use Gemini (Google AI)</span>
              <p className="text-sm text-gray-500 dark:text-gray-300 mt-0.5">
                Summaries are generated via the Gemini API. Requires a valid API key configured in the Gempest tab.
              </p>
            </div>
          </label>
        </div>

        <div className="mt-8 pt-6 border-t border-gray-200 dark:border-gray-700">
          <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100 mb-1">Appearance</h3>
          <p className="text-sm text-gray-500 dark:text-gray-300 mb-4">
            Toggle the application between light and dark mode.
          </p>
          <label className="inline-flex items-center gap-3 cursor-pointer">
            <input
              type="checkbox"
              checked={darkModeEnabled}
              onChange={(event) => setDarkModeEnabled(event.target.checked)}
              className="h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
            />
            <span className="flex items-center gap-2 text-gray-800 dark:text-gray-200 font-medium">
              {darkModeEnabled ? <Moon size={16} /> : <Sun size={16} />}
              {darkModeEnabled ? 'Dark mode enabled' : 'Dark mode disabled'}
            </span>
          </label>
        </div>

        <div className="mt-8 pt-6 border-t border-gray-200 dark:border-gray-700">
          <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100 mb-1">Deletion behavior</h3>
          <p className="text-sm text-gray-500 dark:text-gray-300 mb-4">
            Skip the extra confirmation modal when deleting an email.
          </p>
          <label className="inline-flex items-center gap-3 cursor-pointer">
            <input
              type="checkbox"
              checked={skipDeleteConfirmation}
              onChange={(event) => setSkipDeleteConfirmation(event.target.checked)}
              className="h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
            />
            <span className="text-gray-800 dark:text-gray-200 font-medium">
              Skip delete confirmation
            </span>
          </label>
        </div>

        <button
          onClick={handleSave}
          className="mt-6 flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
        >
          {saved ? <CheckCircle size={16} /> : <Save size={16} />}
          {saved ? 'Saved!' : 'Save'}
        </button>
      </div>
    </div>
  );
};
